#eureka配置
---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1025/eureka

---
spring:
  profiles: prd
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@pig-eureka:1025/eureka