server:
  port: 5002

spring:
  sleuth:
    enabled: false
  rabbitmq:
    host: 123.206.94.20
    port: 5672
    username: lengleng
    password: lengleng

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 123.206.94.20:9200
      cluster: elasticsearch
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1