server:
  port: 5002

spring:
  sleuth:
    enabled: false
  rabbitmq:
    host: 106.14.69.75
    port: 5682
    username: ENC(8VKLl6rejywW+Dch+2S4Fg==)
    password: ENC(8VKLl6rejywW+Dch+2S4Fg==)

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 106.14.69.75:9201
      cluster: elasticsearch
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1